import { Command as CommandPrimitive } from "cmdk";
import { Search } from "lucide-react";
import { forwardRef, type ComponentPropsWithoutRef, type ElementRef, type HTMLAttributes } from "react";
import { cn } from "../../lib/utils";
export const Command=forwardRef<ElementRef<typeof CommandPrimitive>,ComponentPropsWithoutRef<typeof CommandPrimitive>>(({className,...props},ref)=><CommandPrimitive ref={ref} className={cn("flex h-full w-full flex-col overflow-hidden rounded-md bg-popover text-popover-foreground",className)} {...props}/>); Command.displayName=CommandPrimitive.displayName;
export function CommandInput(props: ComponentPropsWithoutRef<typeof CommandPrimitive.Input>) { return <div className="flex items-center border-b px-3"><Search className="mr-2 h-4 w-4 shrink-0 opacity-50"/><CommandPrimitive.Input className="flex h-11 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50" {...props}/></div>; }
export const CommandList=forwardRef<ElementRef<typeof CommandPrimitive.List>,ComponentPropsWithoutRef<typeof CommandPrimitive.List>>(({className,...props},ref)=><CommandPrimitive.List ref={ref} className={cn("max-h-[320px] overflow-y-auto overflow-x-hidden",className)} {...props}/>); CommandList.displayName=CommandPrimitive.List.displayName;
export const CommandEmpty=(props:ComponentPropsWithoutRef<typeof CommandPrimitive.Empty>)=><CommandPrimitive.Empty className="py-6 text-center text-sm" {...props}/>;
export const CommandGroup=forwardRef<ElementRef<typeof CommandPrimitive.Group>,ComponentPropsWithoutRef<typeof CommandPrimitive.Group>>(({className,...props},ref)=><CommandPrimitive.Group ref={ref} className={cn("overflow-hidden p-1 text-foreground [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground",className)} {...props}/>); CommandGroup.displayName=CommandPrimitive.Group.displayName;
export const CommandItem=forwardRef<ElementRef<typeof CommandPrimitive.Item>,ComponentPropsWithoutRef<typeof CommandPrimitive.Item>>(({className,...props},ref)=><CommandPrimitive.Item ref={ref} className={cn("relative flex cursor-default select-none items-center rounded-sm px-2 py-2 text-sm outline-none data-[disabled=true]:pointer-events-none data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground data-[disabled=true]:opacity-50",className)} {...props}/>); CommandItem.displayName=CommandPrimitive.Item.displayName;
export function CommandShortcut({className,...props}:HTMLAttributes<HTMLSpanElement>){return <span className={cn("ml-auto text-xs tracking-widest text-muted-foreground",className)} {...props}/>;}

