import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu";
import { forwardRef, type ComponentPropsWithoutRef, type ElementRef } from "react";
import { cn } from "../../lib/utils";
export const DropdownMenu=DropdownMenuPrimitive.Root;
export const DropdownMenuTrigger=DropdownMenuPrimitive.Trigger;
export const DropdownMenuSeparator=forwardRef<ElementRef<typeof DropdownMenuPrimitive.Separator>,ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Separator>>(({className,...props},ref)=><DropdownMenuPrimitive.Separator ref={ref} className={cn("-mx-1 my-1 h-px bg-muted",className)} {...props}/>); DropdownMenuSeparator.displayName=DropdownMenuPrimitive.Separator.displayName;
export const DropdownMenuContent=forwardRef<ElementRef<typeof DropdownMenuPrimitive.Content>,ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Content>>(({className,sideOffset=4,...props},ref)=><DropdownMenuPrimitive.Portal><DropdownMenuPrimitive.Content ref={ref} sideOffset={sideOffset} className={cn("z-50 min-w-40 overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md",className)} {...props}/></DropdownMenuPrimitive.Portal>); DropdownMenuContent.displayName=DropdownMenuPrimitive.Content.displayName;
export const DropdownMenuItem=forwardRef<ElementRef<typeof DropdownMenuPrimitive.Item>,ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Item>>(({className,...props},ref)=><DropdownMenuPrimitive.Item ref={ref} className={cn("relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50",className)} {...props}/>); DropdownMenuItem.displayName=DropdownMenuPrimitive.Item.displayName;
export const DropdownMenuLabel=forwardRef<ElementRef<typeof DropdownMenuPrimitive.Label>,ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Label>>(({className,...props},ref)=><DropdownMenuPrimitive.Label ref={ref} className={cn("px-2 py-1.5 text-sm font-semibold",className)} {...props}/>); DropdownMenuLabel.displayName=DropdownMenuPrimitive.Label.displayName;

